insert into addetti (id, nome, cognome, email, indirizzo) values (1, 'Lizzie', 'Vaudin', 'lvaudin0@furl.net', '2393 Clove Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (2, 'Kirstin', 'Bordman', 'kbordman1@shutterfly.com', '7 Green Ridge Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (3, 'Sapphire', 'Huetson', 'shuetson2@cnn.com', '6 Brown Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (4, 'Sebastien', 'Faulconer', 'sfaulconer3@miitbeian.gov.cn', '678 Fairfield Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (5, 'Jed', 'Crippen', 'jcrippen4@ibm.com', '0581 Fuller Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (6, 'Kinny', 'Calow', 'kcalow5@ftc.gov', '78796 Saint Paul Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (7, 'Lorine', 'Fearnehough', 'lfearnehough6@google.pl', '246 Sheridan Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (8, 'Caye', 'Owthwaite', 'cowthwaite7@thetimes.co.uk', '023 Farwell Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (9, 'Gail', 'Leak', 'gleak8@timesonline.co.uk', '34582 Ridgeview Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (10, 'Amata', 'Wolfindale', 'awolfindale9@admin.ch', '386 Maywood Junction');
insert into addetti (id, nome, cognome, email, indirizzo) values (11, 'Hetty', 'De Ortega', 'hdeortegaa@squarespace.com', '5496 Truax Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (12, 'Sharon', 'Lawty', 'slawtyb@nbcnews.com', '1237 Buhler Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (13, 'Harriette', 'Spurier', 'hspurierc@hugedomains.com', '79010 South Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (14, 'Camey', 'Cuckson', 'ccucksond@theguardian.com', '4 David Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (15, 'Judie', 'Kynett', 'jkynette@weibo.com', '30452 Stang Park');
insert into addetti (id, nome, cognome, email, indirizzo) values (16, 'Brita', 'Shellcross', 'bshellcrossf@elegantthemes.com', '55686 Debs Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (17, 'Ulla', 'Askin', 'uasking@timesonline.co.uk', '780 Truax Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (18, 'Murvyn', 'Sibbons', 'msibbonsh@arizona.edu', '121 Randy Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (19, 'Neal', 'Dyka', 'ndykai@free.fr', '2021 Sunfield Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (20, 'Bliss', 'Guidini', 'bguidinij@washington.edu', '130 Hanson Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (21, 'Cam', 'Kinsett', 'ckinsettk@europa.eu', '2 Ridgeway Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (22, 'Aretha', 'Tregido', 'atregidol@yellowbook.com', '08 Fordem Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (23, 'Barbara', 'Hutten', 'bhuttenm@issuu.com', '969 Duke Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (24, 'Berton', 'Cray', 'bcrayn@washingtonpost.com', '3 Hallows Pass');
insert into addetti (id, nome, cognome, email, indirizzo) values (25, 'Frances', 'Drew-Clifton', 'fdrewcliftono@mayoclinic.com', '49772 Bartillon Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (26, 'Trueman', 'Wloch', 'twlochp@nbcnews.com', '7 Menomonie Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (27, 'Ree', 'Lynn', 'rlynnq@eepurl.com', '021 Dovetail Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (28, 'Jaquenetta', 'Brikner', 'jbriknerr@homestead.com', '72 Forest Run Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (29, 'Karissa', 'Petrosian', 'kpetrosians@symantec.com', '51 Arkansas Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (30, 'Molli', 'Minchell', 'mminchellt@skype.com', '878 Straubel Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (31, 'Gertie', 'Broseman', 'gbrosemanu@shop-pro.jp', '799 Fairview Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (32, 'Raleigh', 'Tomalin', 'rtomalinv@booking.com', '599 Moose Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (33, 'Beckie', 'D''Angeli', 'bdangeliw@thetimes.co.uk', '64223 Barby Parkway');
insert into addetti (id, nome, cognome, email, indirizzo) values (34, 'Beverley', 'Quail', 'bquailx@loc.gov', '334 Esch Pass');
insert into addetti (id, nome, cognome, email, indirizzo) values (35, 'Ellissa', 'Napton', 'enaptony@w3.org', '51757 Mcbride Parkway');
insert into addetti (id, nome, cognome, email, indirizzo) values (36, 'Carling', 'Bake', 'cbakez@epa.gov', '19881 Northland Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (37, 'Lurleen', 'Duncanson', 'lduncanson10@flavors.me', '42 Fairview Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (38, 'Eran', 'Guys', 'eguys11@ustream.tv', '6 Raven Park');
insert into addetti (id, nome, cognome, email, indirizzo) values (39, 'Dwain', 'Laminman', 'dlaminman12@so-net.ne.jp', '21 Crownhardt Pass');
insert into addetti (id, nome, cognome, email, indirizzo) values (40, 'Woodman', 'Serrels', 'wserrels13@freewebs.com', '298 School Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (41, 'Hermy', 'Tooker', 'htooker14@cyberchimps.com', '12 Sheridan Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (42, 'Milton', 'MacGall', 'mmacgall15@timesonline.co.uk', '07812 Oriole Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (43, 'Gardner', 'Prin', 'gprin16@japanpost.jp', '05 Bartillon Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (44, 'Leonelle', 'Gettens', 'lgettens17@posterous.com', '38403 Loftsgordon Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (45, 'Micky', 'Fotheringham', 'mfotheringham18@theguardian.com', '840 Bellgrove Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (46, 'Rob', 'MacNair', 'rmacnair19@chron.com', '769 North Parkway');
insert into addetti (id, nome, cognome, email, indirizzo) values (47, 'Ignacius', 'Pridden', 'ipridden1a@angelfire.com', '639 Ruskin Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (48, 'Tyrone', 'Reeders', 'treeders1b@hao123.com', '2 Dakota Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (49, 'Pietra', 'Ash', 'pash1c@youku.com', '1056 Badeau Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (50, 'Ashleigh', 'Traut', 'atraut1d@reuters.com', '14106 Schmedeman Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (51, 'Margaretha', 'Kew', 'mkew1e@hp.com', '749 Esker Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (52, 'Ben', 'Minichillo', 'bminichillo1f@sciencedirect.com', '1 Arapahoe Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (53, 'Zerk', 'Lomasna', 'zlomasna1g@zdnet.com', '9 American Ash Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (54, 'Ninette', 'Riquet', 'nriquet1h@ow.ly', '0764 Knutson Junction');
insert into addetti (id, nome, cognome, email, indirizzo) values (55, 'Robin', 'Clayworth', 'rclayworth1i@51.la', '66 Fairfield Parkway');
insert into addetti (id, nome, cognome, email, indirizzo) values (56, 'Munroe', 'Bubbins', 'mbubbins1j@google.fr', '11 Loftsgordon Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (57, 'Gretal', 'Beardsall', 'gbeardsall1k@state.tx.us', '27543 Clyde Gallagher Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (58, 'Vivianne', 'Newe', 'vnewe1l@yellowpages.com', '477 Dahle Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (59, 'Jordana', 'Cristofol', 'jcristofol1m@ucoz.com', '87 Farwell Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (60, 'Chelsy', 'Figgures', 'cfiggures1n@wordpress.com', '5999 Golf Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (61, 'Erick', 'Hinder', 'ehinder1o@tripadvisor.com', '599 Sunbrook Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (62, 'Christie', 'Gunthorp', 'cgunthorp1p@amazon.co.jp', '5462 Corscot Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (63, 'Nellie', 'Paradyce', 'nparadyce1q@linkedin.com', '84 Summit Pass');
insert into addetti (id, nome, cognome, email, indirizzo) values (64, 'Hodge', 'Mander', 'hmander1r@webeden.co.uk', '1113 Upham Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (65, 'Ignazio', 'Haster', 'ihaster1s@360.cn', '16 Grover Park');
insert into addetti (id, nome, cognome, email, indirizzo) values (66, 'Quintus', 'Merricks', 'qmerricks1t@chron.com', '79 Banding Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (67, 'Gwyn', 'Gascar', 'ggascar1u@list-manage.com', '83 Northport Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (68, 'Rolfe', 'Maudett', 'rmaudett1v@example.com', '861 Maple Wood Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (69, 'Rowney', 'Bentame', 'rbentame1w@deliciousdays.com', '56937 Eagle Crest Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (70, 'Baudoin', 'Bowller', 'bbowller1x@ameblo.jp', '54 Holy Cross Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (71, 'Jules', 'Maybey', 'jmaybey1y@php.net', '59633 Knutson Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (72, 'Donna', 'Yerlett', 'dyerlett1z@jiathis.com', '2 Barnett Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (73, 'Laurie', 'Cicchillo', 'lcicchillo20@accuweather.com', '62358 Glacier Hill Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (74, 'Hubert', 'Foker', 'hfoker21@nifty.com', '0982 Corry Way');
insert into addetti (id, nome, cognome, email, indirizzo) values (75, 'Araldo', 'Hunter', 'ahunter22@wired.com', '3 Charing Cross Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (76, 'Levy', 'Subhan', 'lsubhan23@about.me', '72 Mendota Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (77, 'Miner', 'Stuehmeyer', 'mstuehmeyer24@smugmug.com', '7 Tennessee Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (78, 'Sheba', 'Dassindale', 'sdassindale25@microsoft.com', '384 Debs Junction');
insert into addetti (id, nome, cognome, email, indirizzo) values (79, 'Benny', 'Sorley', 'bsorley26@taobao.com', '68 Graedel Way');
insert into addetti (id, nome, cognome, email, indirizzo) values (80, 'Chandal', 'Gantley', 'cgantley27@taobao.com', '27901 Charing Cross Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (81, 'Bordy', 'Ponceford', 'bponceford28@yellowbook.com', '01092 Acker Junction');
insert into addetti (id, nome, cognome, email, indirizzo) values (82, 'Derick', 'Haynesford', 'dhaynesford29@blogs.com', '52 Harbort Parkway');
insert into addetti (id, nome, cognome, email, indirizzo) values (83, 'Arin', 'Maypother', 'amaypother2a@privacy.gov.au', '27 Knutson Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (84, 'Mirabelle', 'Aleksahkin', 'maleksahkin2b@wired.com', '152 Badeau Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (85, 'Jacquette', 'Fley', 'jfley2c@craigslist.org', '99711 Nova Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (86, 'Hannis', 'Kelling', 'hkelling2d@wordpress.org', '8 Cascade Pass');
insert into addetti (id, nome, cognome, email, indirizzo) values (87, 'Dominik', 'Sleet', 'dsleet2e@bluehost.com', '683 Meadow Vale Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (88, 'Donalt', 'Cumbers', 'dcumbers2f@telegraph.co.uk', '0 Chive Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (89, 'Tracey', 'Beartup', 'tbeartup2g@slideshare.net', '02 Granby Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (90, 'Traci', 'Artz', 'tartz2h@ft.com', '6 Cherokee Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (91, 'Karyl', 'Pinck', 'kpinck2i@themeforest.net', '88 Comanche Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (92, 'Sherie', 'Childers', 'schilders2j@house.gov', '6 Roxbury Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (93, 'Romona', 'Klimke', 'rklimke2k@paginegialle.it', '85318 Sunfield Way');
insert into addetti (id, nome, cognome, email, indirizzo) values (94, 'Adan', 'D''Aguanno', 'adaguanno2l@state.gov', '025 Charing Cross Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (95, 'Noelle', 'Eager', 'neager2m@jiathis.com', '65 Caliangt Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (96, 'Arlena', 'O''Hoey', 'aohoey2n@rediff.com', '02 Bonner Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (97, 'Evyn', 'Jolly', 'ejolly2o@businesswire.com', '063 Loomis Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (98, 'Boonie', 'Ager', 'bager2p@opensource.org', '8736 Longview Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (99, 'Quill', 'Lyon', 'qlyon2q@php.net', '11 Manitowish Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (100, 'Lissie', 'Lambswood', 'llambswood2r@auda.org.au', '6 Rieder Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (101, 'Gill', 'MacCartney', 'gmaccartney2s@nyu.edu', '18 Petterle Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (102, 'Kelly', 'Thunnercliffe', 'kthunnercliffe2t@geocities.jp', '809 Cordelia Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (103, 'Zilvia', 'Twiddy', 'ztwiddy2u@foxnews.com', '6 Troy Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (104, 'Chad', 'Sapey', 'csapey2v@usda.gov', '171 Meadow Vale Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (105, 'Yorker', 'Petts', 'ypetts2w@apache.org', '85432 Ronald Regan Court');
insert into addetti (id, nome, cognome, email, indirizzo) values (106, 'Janifer', 'Robbe', 'jrobbe2x@howstuffworks.com', '420 Mesta Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (107, 'Marylin', 'Wrates', 'mwrates2y@paypal.com', '4 Pleasure Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (108, 'Nertie', 'Boother', 'nboother2z@rakuten.co.jp', '464 Nancy Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (109, 'Yard', 'Walklate', 'ywalklate30@china.com.cn', '815 Ridge Oak Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (110, 'Cynthea', 'Studde', 'cstudde31@sfgate.com', '8626 Artisan Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (111, 'Agna', 'Vasler', 'avasler32@soundcloud.com', '18936 Kensington Center');
insert into addetti (id, nome, cognome, email, indirizzo) values (112, 'Nat', 'Buttress', 'nbuttress33@livejournal.com', '7 Summit Alley');
insert into addetti (id, nome, cognome, email, indirizzo) values (113, 'Rhea', 'Tunmore', 'rtunmore34@dedecms.com', '7571 Debs Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (114, 'Codie', 'Colledge', 'ccolledge35@godaddy.com', '346 Grasskamp Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (115, 'Emilie', 'Deville', 'edeville36@wordpress.com', '0911 Eliot Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (116, 'Taber', 'Bibby', 'tbibby37@smh.com.au', '22128 Myrtle Lane');
insert into addetti (id, nome, cognome, email, indirizzo) values (117, 'Jaquenette', 'Aylwin', 'jaylwin38@scientificamerican.com', '1327 Claremont Junction');
insert into addetti (id, nome, cognome, email, indirizzo) values (118, 'Corly', 'Gouley', 'cgouley39@squarespace.com', '63936 Eagan Circle');
insert into addetti (id, nome, cognome, email, indirizzo) values (119, 'Francklin', 'Krojn', 'fkrojn3a@vistaprint.com', '2493 Talisman Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (120, 'Cinda', 'Rodie', 'crodie3b@wiley.com', '524 Crest Line Park');
insert into addetti (id, nome, cognome, email, indirizzo) values (121, 'Cort', 'Sivyour', 'csivyour3c@1und1.de', '62 Helena Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (122, 'Lanita', 'Spurret', 'lspurret3d@java.com', '69 Doe Crossing Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (123, 'Loren', 'Shieber', 'lshieber3e@omniture.com', '72594 Rutledge Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (124, 'Oliver', 'Jockle', 'ojockle3f@netscape.com', '4 Blue Bill Park Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (125, 'Dorri', 'Baggarley', 'dbaggarley3g@scribd.com', '6479 Mcbride Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (126, 'Bethena', 'Mertel', 'bmertel3h@devhub.com', '59058 Declaration Drive');
insert into addetti (id, nome, cognome, email, indirizzo) values (127, 'Waverly', 'Strainge', 'wstrainge3i@i2i.jp', '80394 Bartelt Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (128, 'Latrina', 'Dingle', 'ldingle3j@apache.org', '97 Golf Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (129, 'Julita', 'Warboy', 'jwarboy3k@newsvine.com', '51 Waubesa Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (130, 'Elyssa', 'Dannel', 'edannel3l@amazon.co.uk', '7709 Shasta Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (131, 'Marlowe', 'Kristufek', 'mkristufek3m@etsy.com', '215 Derek Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (132, 'Michal', 'Dunkirk', 'mdunkirk3n@free.fr', '277 Walton Avenue');
insert into addetti (id, nome, cognome, email, indirizzo) values (133, 'Graham', 'Beebe', 'gbeebe3o@pcworld.com', '0302 Stuart Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (134, 'Andree', 'Duckworth', 'aduckworth3p@unblog.fr', '376 Maywood Way');
insert into addetti (id, nome, cognome, email, indirizzo) values (135, 'Brendis', 'Ganley', 'bganley3q@constantcontact.com', '04522 Eagle Crest Road');
insert into addetti (id, nome, cognome, email, indirizzo) values (136, 'Elberta', 'Wason', 'ewason3r@desdev.cn', '98353 Onsgard Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (137, 'Stephenie', 'Agglio', 'sagglio3s@zimbio.com', '70 Kenwood Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (138, 'Yoshiko', 'Boldero', 'yboldero3t@123-reg.co.uk', '4 Green Place');
insert into addetti (id, nome, cognome, email, indirizzo) values (139, 'Aindrea', 'Sirr', 'asirr3u@google.ru', '11 Lillian Street');
insert into addetti (id, nome, cognome, email, indirizzo) values (140, 'Chelsie', 'Leavry', 'cleavry3v@xrea.com', '6846 Kropf Point');
insert into addetti (id, nome, cognome, email, indirizzo) values (141, 'George', 'Dabner', 'gdabner3w@instagram.com', '04838 Crest Line Way');
insert into addetti (id, nome, cognome, email, indirizzo) values (142, 'Elga', 'Dearnley', 'edearnley3x@bloglines.com', '6 Lotheville Park');
insert into addetti (id, nome, cognome, email, indirizzo) values (143, 'Zollie', 'Dunnico', 'zdunnico3y@stanford.edu', '5 Evergreen Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (144, 'Saraann', 'Trunkfield', 'strunkfield3z@chicagotribune.com', '244 Riverside Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (145, 'Hephzibah', 'Tyce', 'htyce40@reverbnation.com', '62483 Kensington Plaza');
insert into addetti (id, nome, cognome, email, indirizzo) values (146, 'Irvine', 'Echelle', 'iechelle41@gravatar.com', '410 Northwestern Crossing');
insert into addetti (id, nome, cognome, email, indirizzo) values (147, 'Immanuel', 'Oda', 'ioda42@state.tx.us', '3 Ryan Trail');
insert into addetti (id, nome, cognome, email, indirizzo) values (148, 'Nolie', 'Aliberti', 'naliberti43@yelp.com', '1 Havey Hill');
insert into addetti (id, nome, cognome, email, indirizzo) values (149, 'Geoff', 'Kinkaid', 'gkinkaid44@bravesites.com', '439 Beilfuss Terrace');
insert into addetti (id, nome, cognome, email, indirizzo) values (150, 'Bernie', 'Budnik', 'bbudnik45@ibm.com', '77884 Sunfield Street');
