insert into generi (id, nome, numero_esemplari, casa_id) values (1, 'Monkey, black spider', 0, 33);
insert into generi (id, nome, numero_esemplari, casa_id) values (2, 'Zorro, common', 0, 3);
insert into generi (id, nome, numero_esemplari, casa_id) values (3, 'Deer, black-tailed', 0, 41);
insert into generi (id, nome, numero_esemplari, casa_id) values (4, 'White rhinoceros', 0, 118);
insert into generi (id, nome, numero_esemplari, casa_id) values (5, 'Southern white-crowned shrike', 0, 20);
insert into generi (id, nome, numero_esemplari, casa_id) values (6, 'Magpie, australian', 0, 77);
insert into generi (id, nome, numero_esemplari, casa_id) values (7, 'Gazer, sun', 0, 143);
insert into generi (id, nome, numero_esemplari, casa_id) values (8, 'Goldeneye, common', 0, 34);
insert into generi (id, nome, numero_esemplari, casa_id) values (9, 'Weeper capuchin', 0, 22);
insert into generi (id, nome, numero_esemplari, casa_id) values (10, 'Asian water buffalo', 0, 2);
insert into generi (id, nome, numero_esemplari, casa_id) values (11, 'Duck, blue', 0, 101);
insert into generi (id, nome, numero_esemplari, casa_id) values (12, 'Loris, slender', 0, 82);
insert into generi (id, nome, numero_esemplari, casa_id) values (13, 'Southern boubou', 0, 17);
insert into generi (id, nome, numero_esemplari, casa_id) values (14, 'Heron, black-crowned night', 0, 20);
insert into generi (id, nome, numero_esemplari, casa_id) values (15, 'Mongoose, yellow', 0, 127);
insert into generi (id, nome, numero_esemplari, casa_id) values (16, 'Fox, pampa gray', 0, 86);
insert into generi (id, nome, numero_esemplari, casa_id) values (17, 'Nyala', 0, 85);
insert into generi (id, nome, numero_esemplari, casa_id) values (18, 'Hawk, red-tailed', 0, 142);
insert into generi (id, nome, numero_esemplari, casa_id) values (19, 'Woodcock, american', 0, 102);
insert into generi (id, nome, numero_esemplari, casa_id) values (20, 'Common palm civet', 0, 81);
insert into generi (id, nome, numero_esemplari, casa_id) values (21, 'Booby, blue-faced', 0, 114);
insert into generi (id, nome, numero_esemplari, casa_id) values (22, 'Ornate rock dragon', 0, 119);
insert into generi (id, nome, numero_esemplari, casa_id) values (23, 'White-headed vulture', 0, 149);
insert into generi (id, nome, numero_esemplari, casa_id) values (24, 'Dove, galapagos', 0, 50);
insert into generi (id, nome, numero_esemplari, casa_id) values (25, 'Ground legaan', 0, 67);
insert into generi (id, nome, numero_esemplari, casa_id) values (26, 'Arctic fox', 0, 73);
insert into generi (id, nome, numero_esemplari, casa_id) values (27, 'Four-striped grass mouse', 0, 74);
insert into generi (id, nome, numero_esemplari, casa_id) values (28, 'Gemsbok', 0, 146);
insert into generi (id, nome, numero_esemplari, casa_id) values (29, 'Ringtail, common', 0, 32);
insert into generi (id, nome, numero_esemplari, casa_id) values (30, 'Asian water buffalo', 0, 119);
insert into generi (id, nome, numero_esemplari, casa_id) values (31, 'Tasmanian devil', 0, 110);
insert into generi (id, nome, numero_esemplari, casa_id) values (32, 'Rhinoceros, square-lipped', 0, 28);
insert into generi (id, nome, numero_esemplari, casa_id) values (33, 'Eastern diamondback rattlesnake', 0, 21);
insert into generi (id, nome, numero_esemplari, casa_id) values (34, 'Indian jackal', 0, 45);
insert into generi (id, nome, numero_esemplari, casa_id) values (35, 'Legaan, water', 0, 86);
insert into generi (id, nome, numero_esemplari, casa_id) values (36, 'Hornbill, leadbeateri''s ground', 0, 112);
insert into generi (id, nome, numero_esemplari, casa_id) values (37, 'Cliffchat, mocking', 0, 117);
insert into generi (id, nome, numero_esemplari, casa_id) values (38, 'Beaver, north american', 0, 104);
insert into generi (id, nome, numero_esemplari, casa_id) values (39, 'Ibis, sacred', 0, 99);
insert into generi (id, nome, numero_esemplari, casa_id) values (40, 'Javan gold-spotted mongoose', 0, 150);
insert into generi (id, nome, numero_esemplari, casa_id) values (41, 'Golden jackal', 0, 42);
insert into generi (id, nome, numero_esemplari, casa_id) values (42, 'Vulture, bengal', 0, 42);
insert into generi (id, nome, numero_esemplari, casa_id) values (43, 'Cat, jungle', 0, 95);
insert into generi (id, nome, numero_esemplari, casa_id) values (44, 'Ground monitor (unidentified)', 0, 88);
insert into generi (id, nome, numero_esemplari, casa_id) values (45, 'Stanley bustard', 0, 74);
insert into generi (id, nome, numero_esemplari, casa_id) values (46, 'Western palm tanager (unidentified)', 0, 36);
insert into generi (id, nome, numero_esemplari, casa_id) values (47, 'Armadillo, seven-banded', 0, 74);
insert into generi (id, nome, numero_esemplari, casa_id) values (48, 'Warthog', 0, 44);
insert into generi (id, nome, numero_esemplari, casa_id) values (49, 'Worm snake (unidentified)', 0, 101);
insert into generi (id, nome, numero_esemplari, casa_id) values (50, 'Sloth, two-toed', 0, 124);
insert into generi (id, nome, numero_esemplari, casa_id) values (51, 'Pig-tailed macaque', 0, 39);
insert into generi (id, nome, numero_esemplari, casa_id) values (52, 'Crow, pied', 0, 110);
insert into generi (id, nome, numero_esemplari, casa_id) values (53, 'Hoffman''s sloth', 0, 51);
insert into generi (id, nome, numero_esemplari, casa_id) values (54, 'Emerald-spotted wood dove', 0, 37);
insert into generi (id, nome, numero_esemplari, casa_id) values (55, 'Quail, gambel''s', 0, 143);
insert into generi (id, nome, numero_esemplari, casa_id) values (56, 'Blue wildebeest', 0, 141);
insert into generi (id, nome, numero_esemplari, casa_id) values (57, 'Deer, red', 0, 137);
insert into generi (id, nome, numero_esemplari, casa_id) values (58, 'Horned rattlesnake', 0, 45);
insert into generi (id, nome, numero_esemplari, casa_id) values (59, 'Blackbuck', 0, 3);
insert into generi (id, nome, numero_esemplari, casa_id) values (60, 'Boa, cook''s tree', 0, 74);
insert into generi (id, nome, numero_esemplari, casa_id) values (61, 'Tammar wallaby', 0, 26);
insert into generi (id, nome, numero_esemplari, casa_id) values (62, 'Common pheasant', 0, 36);
insert into generi (id, nome, numero_esemplari, casa_id) values (63, 'Barrows goldeneye', 0, 52);
insert into generi (id, nome, numero_esemplari, casa_id) values (64, 'Currasow (unidentified)', 0, 53);
insert into generi (id, nome, numero_esemplari, casa_id) values (65, 'Red kangaroo', 0, 35);
insert into generi (id, nome, numero_esemplari, casa_id) values (66, 'Puku', 0, 129);
insert into generi (id, nome, numero_esemplari, casa_id) values (67, 'Cat, miner''s', 0, 15);
insert into generi (id, nome, numero_esemplari, casa_id) values (68, 'Common green iguana', 0, 141);
insert into generi (id, nome, numero_esemplari, casa_id) values (69, 'Chilean flamingo', 0, 49);
insert into generi (id, nome, numero_esemplari, casa_id) values (70, 'American beaver', 0, 88);
insert into generi (id, nome, numero_esemplari, casa_id) values (71, 'Long-billed corella', 0, 24);
insert into generi (id, nome, numero_esemplari, casa_id) values (72, 'Yellow-headed caracara', 0, 11);
insert into generi (id, nome, numero_esemplari, casa_id) values (73, 'Gonolek, burchell''s', 0, 50);
insert into generi (id, nome, numero_esemplari, casa_id) values (74, 'Dove, emerald-spotted wood', 0, 48);
insert into generi (id, nome, numero_esemplari, casa_id) values (75, 'Cape starling', 0, 33);
insert into generi (id, nome, numero_esemplari, casa_id) values (76, 'Badger, european', 0, 54);
insert into generi (id, nome, numero_esemplari, casa_id) values (77, 'Vulture, oriental white-backed', 0, 30);
insert into generi (id, nome, numero_esemplari, casa_id) values (78, 'Squirrel, eurasian red', 0, 136);
insert into generi (id, nome, numero_esemplari, casa_id) values (79, 'Sandhill crane', 0, 30);
insert into generi (id, nome, numero_esemplari, casa_id) values (80, 'Heron, striated', 0, 41);
insert into generi (id, nome, numero_esemplari, casa_id) values (81, 'Eastern indigo snake', 0, 8);
insert into generi (id, nome, numero_esemplari, casa_id) values (82, 'Sandhill crane', 0, 115);
insert into generi (id, nome, numero_esemplari, casa_id) values (83, 'Tasmanian devil', 0, 18);
insert into generi (id, nome, numero_esemplari, casa_id) values (84, 'Fox, grey', 0, 55);
insert into generi (id, nome, numero_esemplari, casa_id) values (85, 'Alligator, american', 0, 131);
insert into generi (id, nome, numero_esemplari, casa_id) values (86, 'River wallaby', 0, 40);
insert into generi (id, nome, numero_esemplari, casa_id) values (87, 'Indian mynah', 0, 33);
insert into generi (id, nome, numero_esemplari, casa_id) values (88, 'Pied butcher bird', 0, 21);
insert into generi (id, nome, numero_esemplari, casa_id) values (89, 'Tayra', 0, 149);
insert into generi (id, nome, numero_esemplari, casa_id) values (90, 'Laughing dove', 0, 128);
insert into generi (id, nome, numero_esemplari, casa_id) values (91, 'Aardwolf', 0, 103);
insert into generi (id, nome, numero_esemplari, casa_id) values (92, 'Common green iguana', 0, 44);
insert into generi (id, nome, numero_esemplari, casa_id) values (93, 'Common wombat', 0, 96);
insert into generi (id, nome, numero_esemplari, casa_id) values (94, 'Stone sheep', 0, 105);
insert into generi (id, nome, numero_esemplari, casa_id) values (95, 'Cormorant, great', 0, 62);
insert into generi (id, nome, numero_esemplari, casa_id) values (96, 'Field flicker', 0, 48);
insert into generi (id, nome, numero_esemplari, casa_id) values (97, 'Canadian river otter', 0, 21);
insert into generi (id, nome, numero_esemplari, casa_id) values (98, 'Weaver, sociable', 0, 93);
insert into generi (id, nome, numero_esemplari, casa_id) values (99, 'Verreaux''s sifaka', 0, 61);
insert into generi (id, nome, numero_esemplari, casa_id) values (100, 'Bee-eater (unidentified)', 0, 71);
insert into generi (id, nome, numero_esemplari, casa_id) values (101, 'White-faced whistling duck', 0, 6);
insert into generi (id, nome, numero_esemplari, casa_id) values (102, 'African polecat', 0, 65);
insert into generi (id, nome, numero_esemplari, casa_id) values (103, 'Steller sea lion', 0, 76);
insert into generi (id, nome, numero_esemplari, casa_id) values (104, 'Gecko, barking', 0, 65);
insert into generi (id, nome, numero_esemplari, casa_id) values (105, 'Giant armadillo', 0, 144);
insert into generi (id, nome, numero_esemplari, casa_id) values (106, 'Stork, marabou', 0, 148);
insert into generi (id, nome, numero_esemplari, casa_id) values (107, 'Fox, silver-backed', 0, 113);
insert into generi (id, nome, numero_esemplari, casa_id) values (108, 'African wild dog', 0, 29);
insert into generi (id, nome, numero_esemplari, casa_id) values (109, 'Stork, white-necked', 0, 68);
insert into generi (id, nome, numero_esemplari, casa_id) values (110, 'White spoonbill', 0, 50);
insert into generi (id, nome, numero_esemplari, casa_id) values (111, 'Seal, northern elephant', 0, 105);
insert into generi (id, nome, numero_esemplari, casa_id) values (112, 'Bent-toed gecko', 0, 68);
insert into generi (id, nome, numero_esemplari, casa_id) values (113, 'Pintail, white-cheeked', 0, 14);
insert into generi (id, nome, numero_esemplari, casa_id) values (114, 'Malabar squirrel', 0, 53);
insert into generi (id, nome, numero_esemplari, casa_id) values (115, 'Yellow-crowned night heron', 0, 127);
insert into generi (id, nome, numero_esemplari, casa_id) values (116, 'Lion, southern sea', 0, 146);
insert into generi (id, nome, numero_esemplari, casa_id) values (117, 'Common pheasant', 0, 81);
insert into generi (id, nome, numero_esemplari, casa_id) values (118, 'Trumpeter, green-winged', 0, 148);
insert into generi (id, nome, numero_esemplari, casa_id) values (119, 'Waterbuck, defassa', 0, 115);
insert into generi (id, nome, numero_esemplari, casa_id) values (120, 'Chilean flamingo', 0, 116);
insert into generi (id, nome, numero_esemplari, casa_id) values (121, 'Lion, california sea', 0, 9);
insert into generi (id, nome, numero_esemplari, casa_id) values (122, 'Groundhog', 0, 148);
insert into generi (id, nome, numero_esemplari, casa_id) values (123, 'Southern black-backed gull', 0, 111);
insert into generi (id, nome, numero_esemplari, casa_id) values (124, 'Red sheep', 0, 1);
insert into generi (id, nome, numero_esemplari, casa_id) values (125, 'Baboon, gelada', 0, 115);
insert into generi (id, nome, numero_esemplari, casa_id) values (126, 'Spotted deer', 0, 89);
insert into generi (id, nome, numero_esemplari, casa_id) values (127, 'Cormorant, little', 0, 1);
insert into generi (id, nome, numero_esemplari, casa_id) values (128, 'Whale, killer', 0, 81);
insert into generi (id, nome, numero_esemplari, casa_id) values (129, 'Galapagos tortoise', 0, 67);
insert into generi (id, nome, numero_esemplari, casa_id) values (130, 'Rainbow lory', 0, 115);
insert into generi (id, nome, numero_esemplari, casa_id) values (131, 'Green vine snake', 0, 40);
insert into generi (id, nome, numero_esemplari, casa_id) values (132, 'Water moccasin', 0, 122);
insert into generi (id, nome, numero_esemplari, casa_id) values (133, 'Crab (unidentified)', 0, 97);
insert into generi (id, nome, numero_esemplari, casa_id) values (134, 'Egyptian cobra', 0, 37);
insert into generi (id, nome, numero_esemplari, casa_id) values (135, 'Lesser flamingo', 0, 43);
insert into generi (id, nome, numero_esemplari, casa_id) values (136, 'Macaw, red and blue', 0, 133);
insert into generi (id, nome, numero_esemplari, casa_id) values (137, 'Dama wallaby', 0, 120);
insert into generi (id, nome, numero_esemplari, casa_id) values (138, 'Kangaroo, western grey', 0, 102);
insert into generi (id, nome, numero_esemplari, casa_id) values (139, 'Red deer', 0, 35);
insert into generi (id, nome, numero_esemplari, casa_id) values (140, 'Crake, african black', 0, 79);
insert into generi (id, nome, numero_esemplari, casa_id) values (141, 'Southern boubou', 0, 60);
insert into generi (id, nome, numero_esemplari, casa_id) values (142, 'Penguin, galapagos', 0, 72);
insert into generi (id, nome, numero_esemplari, casa_id) values (143, 'Cat, african wild', 0, 11);
insert into generi (id, nome, numero_esemplari, casa_id) values (144, 'Pygmy possum', 0, 68);
insert into generi (id, nome, numero_esemplari, casa_id) values (145, 'Pacific gull', 0, 126);
insert into generi (id, nome, numero_esemplari, casa_id) values (146, 'Spotted wood sandpiper', 0, 21);
insert into generi (id, nome, numero_esemplari, casa_id) values (147, 'Eastern grey kangaroo', 0, 138);
insert into generi (id, nome, numero_esemplari, casa_id) values (148, 'Gazer, sun', 0, 4);
insert into generi (id, nome, numero_esemplari, casa_id) values (149, 'Fairy penguin', 0, 34);
insert into generi (id, nome, numero_esemplari, casa_id) values (150, 'Elephant, african', 0, 119);
